plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - coverage/**/*

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  AllowedPatterns:
    - '^\s*#'
    - '^\s*puts'
    - '^\s*raise'

# Style rules
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Rails-specific
Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

# Metrics - be pragmatic with complex services like crawler
Metrics/AbcSize:
  Max: 75
  Exclude:
    - app/services/legislation_crawler_service.rb

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - app/services/legislation_crawler_service.rb

Metrics/MethodLength:
  Max: 80
  Exclude:
    - app/services/legislation_crawler_service.rb

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - app/services/legislation_crawler_service.rb

Metrics/ClassLength:
  Max: 550

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

# Naming
Naming/MethodParameterName:
  MinNameLength: 1

Naming/RescuedExceptionsVariableName:
  PreferredName: e
