countries_data = [
  { code: "us", name: "United States", flag_emoji: "🇺🇸" },
  { code: "br", name: "Brazil", flag_emoji: "🇧🇷" },
  { code: "de", name: "Germany", flag_emoji: "🇩🇪" },
  { code: "fr", name: "France", flag_emoji: "🇫🇷" },
  { code: "gb", name: "United Kingdom", flag_emoji: "🇬🇧" },
  { code: "ca", name: "Canada", flag_emoji: "🇨🇦" },
  { code: "au", name: "Australia", flag_emoji: "🇦🇺" },
  { code: "jp", name: "Japan", flag_emoji: "🇯🇵" },
  { code: "cn", name: "China", flag_emoji: "🇨🇳" },
  { code: "in", name: "India", flag_emoji: "🇮🇳" },
  { code: "mx", name: "Mexico", flag_emoji: "🇲🇽" },
  { code: "es", name: "Spain", flag_emoji: "🇪🇸" },
  { code: "it", name: "Italy", flag_emoji: "🇮🇹" },
  { code: "nl", name: "Netherlands", flag_emoji: "🇳🇱" },
  { code: "se", name: "Sweden", flag_emoji: "🇸🇪" },
  { code: "ch", name: "Switzerland", flag_emoji: "🇨🇭" },
  { code: "at", name: "Austria", flag_emoji: "🇦🇹" },
  { code: "be", name: "Belgium", flag_emoji: "🇧🇪" },
  { code: "gr", name: "Greece", flag_emoji: "🇬🇷" },
  { code: "pt", name: "Portugal", flag_emoji: "🇵🇹" },
  { code: "nz", name: "New Zealand", flag_emoji: "🇳🇿" },
  { code: "sg", name: "Singapore", flag_emoji: "🇸🇬" },
  { code: "hk", name: "Hong Kong", flag_emoji: "🇭🇰" },
  { code: "kr", name: "South Korea", flag_emoji: "🇰🇷" },
  { code: "th", name: "Thailand", flag_emoji: "🇹🇭" },
  { code: "ph", name: "Philippines", flag_emoji: "🇵🇭" },
  { code: "my", name: "Malaysia", flag_emoji: "🇲🇾" },
  { code: "id", name: "Indonesia", flag_emoji: "🇮🇩" },
  { code: "vn", name: "Vietnam", flag_emoji: "🇻🇳" },
  { code: "ar", name: "Argentina", flag_emoji: "🇦🇷" },
  { code: "cl", name: "Chile", flag_emoji: "🇨🇱" },
  { code: "co", name: "Colombia", flag_emoji: "🇨🇴" },
  { code: "pe", name: "Peru", flag_emoji: "🇵🇪" },
  { code: "za", name: "South Africa", flag_emoji: "🇿🇦" },
  { code: "eg", name: "Egypt", flag_emoji: "🇪🇬" },
  { code: "ng", name: "Nigeria", flag_emoji: "🇳🇬" },
  { code: "ke", name: "Kenya", flag_emoji: "🇰🇪" },
  { code: "ae", name: "United Arab Emirates", flag_emoji: "🇦🇪" },
  { code: "sa", name: "Saudi Arabia", flag_emoji: "🇸🇦" },
  { code: "il", name: "Israel", flag_emoji: "🇮🇱" },
  { code: "ru", name: "Russia", flag_emoji: "🇷🇺" },
  { code: "ua", name: "Ukraine", flag_emoji: "🇺🇦" },
  { code: "pl", name: "Poland", flag_emoji: "🇵🇱" },
  { code: "cz", name: "Czech Republic", flag_emoji: "🇨🇿" },
  { code: "hu", name: "Hungary", flag_emoji: "🇭🇺" },
  { code: "ro", name: "Romania", flag_emoji: "🇷🇴" },
  { code: "bg", name: "Bulgaria", flag_emoji: "🇧🇬" },
  { code: "hr", name: "Croatia", flag_emoji: "🇭🇷" },
  { code: "ie", name: "Ireland", flag_emoji: "🇮🇪" },
  { code: "dk", name: "Denmark", flag_emoji: "🇩🇰" },
  { code: "fi", name: "Finland", flag_emoji: "🇫🇮" },
  { code: "no", name: "Norway", flag_emoji: "🇳🇴" },
  { code: "is", name: "Iceland", flag_emoji: "🇮🇸" },
  { code: "lv", name: "Latvia", flag_emoji: "🇱🇻" },
  { code: "lt", name: "Lithuania", flag_emoji: "🇱🇹" },
  { code: "ee", name: "Estonia", flag_emoji: "🇪🇪" },
  { code: "sk", name: "Slovakia", flag_emoji: "🇸🇰" },
  { code: "si", name: "Slovenia", flag_emoji: "🇸🇮" },
  { code: "mt", name: "Malta", flag_emoji: "🇲🇹" },
  { code: "cy", name: "Cyprus", flag_emoji: "🇨🇾" },
  { code: "lu", name: "Luxembourg", flag_emoji: "🇱🇺" },
  { code: "tr", name: "Türkiye", flag_emoji: "🇹🇷" },
  { code: "kz", name: "Kazakhstan", flag_emoji: "🇰🇿" },
  { code: "ge", name: "Georgia", flag_emoji: "🇬🇪" },
  { code: "az", name: "Azerbaijan", flag_emoji: "🇦🇿" },
  { code: "am", name: "Armenia", flag_emoji: "🇦🇲" },
  { code: "pk", name: "Pakistan", flag_emoji: "🇵🇰" },
  { code: "bd", name: "Bangladesh", flag_emoji: "🇧🇩" },
  { code: "lk", name: "Sri Lanka", flag_emoji: "🇱🇰" },
  { code: "np", name: "Nepal", flag_emoji: "🇳🇵" },
  { code: "kh", name: "Cambodia", flag_emoji: "🇰🇭" },
  { code: "la", name: "Laos", flag_emoji: "🇱🇦" },
  { code: "mm", name: "Myanmar", flag_emoji: "🇲🇲" },
  { code: "tw", name: "Taiwan", flag_emoji: "🇹🇼" },
  { code: "mz", name: "Mozambique", flag_emoji: "🇲🇿" },
  { code: "tz", name: "Tanzania", flag_emoji: "🇹🇿" },
  { code: "ug", name: "Uganda", flag_emoji: "🇺🇬" },
  { code: "gh", name: "Ghana", flag_emoji: "🇬🇭" },
  { code: "sn", name: "Senegal", flag_emoji: "🇸🇳" },
  { code: "ci", name: "Côte d'Ivoire", flag_emoji: "🇨🇮" },
  { code: "tn", name: "Tunisia", flag_emoji: "🇹🇳" },
  { code: "dz", name: "Algeria", flag_emoji: "🇩🇿" },
  { code: "ma", name: "Morocco", flag_emoji: "🇲🇦" },
  { code: "jo", name: "Jordan", flag_emoji: "🇯🇴" },
  { code: "lb", name: "Lebanon", flag_emoji: "🇱🇧" },
  { code: "kw", name: "Kuwait", flag_emoji: "🇰🇼" },
  { code: "qa", name: "Qatar", flag_emoji: "🇶🇦" },
  { code: "bh", name: "Bahrain", flag_emoji: "🇧🇭" },
  { code: "om", name: "Oman", flag_emoji: "🇴🇲" },
  { code: "yr", name: "Yemen", flag_emoji: "🇾🇪" },
  { code: "ir", name: "Iran", flag_emoji: "🇮🇷" },
  { code: "af", name: "Afghanistan", flag_emoji: "🇦🇫" },
  { code: "iq", name: "Iraq", flag_emoji: "🇮🇶" },
  { code: "sy", name: "Syria", flag_emoji: "🇸🇾" },
  { code: "ve", name: "Venezuela", flag_emoji: "🇻🇪" },
  { code: "ec", name: "Ecuador", flag_emoji: "🇪🇨" },
  { code: "bo", name: "Bolivia", flag_emoji: "🇧🇴" },
  { code: "py", name: "Paraguay", flag_emoji: "🇵🇾" },
  { code: "uy", name: "Uruguay", flag_emoji: "🇺🇾" },
  { code: "cr", name: "Costa Rica", flag_emoji: "🇨🇷" },
  { code: "pa", name: "Panama", flag_emoji: "🇵🇦" },
  { code: "do", name: "Dominican Republic", flag_emoji: "🇩🇴" },
  { code: "cu", name: "Cuba", flag_emoji: "🇨🇺" },
  { code: "jm", name: "Jamaica", flag_emoji: "🇯🇲" },
  { code: "tt", name: "Trinidad and Tobago", flag_emoji: "🇹🇹" },
  { code: "bb", name: "Barbados", flag_emoji: "🇧🇧" },
  { code: "gy", name: "Guyana", flag_emoji: "🇬🇾" },
  { code: "sr", name: "Suriname", flag_emoji: "🇸🇷" },
  { code: "bz", name: "Belize", flag_emoji: "🇧🇿" },
  { code: "sv", name: "El Salvador", flag_emoji: "🇸🇻" },
  { code: "gt", name: "Guatemala", flag_emoji: "🇬🇹" },
  { code: "hn", name: "Honduras", flag_emoji: "🇭🇳" },
  { code: "ni", name: "Nicaragua", flag_emoji: "🇳🇮" },
  { code: "fj", name: "Fiji", flag_emoji: "🇫🇯" },
]

countries_data.each do |data|
  Country.find_or_create_by!(code: data[:code]) do |country|
    country.name = data[:name]
    country.flag_emoji = data[:flag_emoji]
  end
end

puts "✅ Seeded #{Country.count} countries"
